vpNext:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - CORE_NEXT=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_PKI_ECA_PADDR=membersrvc0:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc0:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc0:7054
    - CORE_PEER_PKI_TLS_ROOTCERT_FILE=./bddtests/tlsca.cert

